# Address of Pyth contract
pythNetworkAddress: "0xff1a0f4744e8582DF1aE09D5611b887B6a12925C" # Mumbai Testnet address
# Refresh rate of config in seconds
configRefreshRateInSeconds: 3600
priceServiceEndpoint: "https://xc-testnet.pyth.network"
# maximum number of seconds between updates
validTimePeriodSeconds: 86400
# update price if diff between previous price and current exceeds threshold 
# ex: 0.02 = 2%
deviationThreshold: 0.02
# priceIds to check/update
priceIds: 
  - "0xca80ba6dc32e08d06f1aa886011eed1d77c77be9eb761cc10d72b7d0a2fd57a6"
  - "0xf9c0172ba10dfa4d19088d94f5bf61d3b54d5bd7483a322a982e1373ee8ea31b" 
  - "0x26f46723ebaf6eb891b2d5709172346d2221838f39a93d644251a9102c3224c1"